# SPDX-License-Identifier: Apache-2.0
# ruff: noqa: E501
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

DATASET_ID = "sauravsingla08/VertiMosaic-VFL-Benchmark"
MODEL_ID = "sauravsingla08/VertiMosaic-VFL-Reference-Models"
SPACE_URL = "https://huggingface.co/spaces/sauravsingla08/VertiMosaic"
SOURCE_URL = "https://github.com/sauravsingla/VertiMosaic"
DATASET_URL = f"https://huggingface.co/datasets/{DATASET_ID}"
MODEL_URL = f"https://huggingface.co/{MODEL_ID}"


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _fmt_metric(record: dict[str, Any], key: str) -> str:
    value = record.get("test_metrics", {}).get(key)
    return f"{float(value):.4f}" if isinstance(value, (int, float)) else "—"


def _dataset_card(root: Path) -> str:
    manifest = _load_json(root / "summaries" / "manifest.json")
    source_commit = str(manifest.get("source_commit", "unknown"))
    generated_at = str(manifest.get("generated_at_utc", "unknown"))
    core_rows = manifest.get("core_rows", 2000)
    study_rows = manifest.get("study_rows", 1200)
    seed = manifest.get("seed", 42)
    bootstrap = manifest.get("bootstrap_replicates", 200)

    return f"""---
license: apache-2.0
pretty_name: VertiMosaic VFL Benchmark
tags:
- vertical-federated-learning
- federated-learning
- tabular
- privacy-preserving-ml
- distributed-machine-learning
- ml-benchmark
- reproducible-research
- responsible-ai
configs:
- config_name: core-model-comparison
  default: true
  data_files:
  - split: benchmark
    path: data/core_model_comparison.parquet
- config_name: party-ablation
  data_files:
  - split: benchmark
    path: data/party_ablation.parquet
- config_name: partial-overlap
  data_files:
  - split: benchmark
    path: data/partial_overlap.parquet
- config_name: party-dropout
  data_files:
  - split: benchmark
    path: data/party_dropout.parquet
- config_name: feature-drift
  data_files:
  - split: benchmark
    path: data/feature_drift.parquet
---

# VertiMosaic VFL Benchmark

**Five reproducible experiment families for exploring vertical federated learning on heterogeneous tabular data.**

[🚀 Open the interactive Space]({SPACE_URL}) · [🧩 Reference models]({MODEL_URL}) · [💻 Source code]({SOURCE_URL})

This Hub dataset is an **evaluation and reproducibility artifact, not a training corpus**. It packages the canonical evidence generated by VertiMosaic's fully synthetic, CPU-first VFL benchmark so each experiment family can be inspected independently in Dataset Viewer.

## At a glance

| Item | Published evidence |
|---|---|
| Core comparison | {core_rows} synthetic aligned entities |
| Robustness studies | {study_rows} entities per study |
| Experiment seed | `{seed}` |
| Bootstrap replicates | `{bootstrap}` for the core comparison |
| Dataset Viewer configs | 5 |
| Raw feature pooling | **No** |
| Third-party source rows redistributed | **No** |
| Source commit | `{source_commit}` |

## Pick a question

| Question | Configuration | What to inspect |
|---|---|---|
| How do the reference VFL models compare? | `core-model-comparison` | ROC-AUC, PR-AUC, F1, calibration, timing and communication |
| Which parties contribute signal? | `party-ablation` | Bank plus valid subsets of Telecom, Insurance and Retail |
| What changes when entity overlap is incomplete? | `partial-overlap` | intersection-only vs. missing-party-aware training |
| How robust is inference to unavailable parties? | `party-dropout` | training/inference availability scenarios |
| What happens under controlled feature drift? | `feature-drift` | mean, variance, missingness and categorical-frequency shifts |

## Dataset Viewer configurations

The card maps each configuration to exactly one canonical Parquet file so auxiliary provenance files are not inferred as splits.

- `core-model-comparison` — `data/core_model_comparison.parquet` (**default**)
- `party-ablation` — `data/party_ablation.parquet`
- `partial-overlap` — `data/partial_overlap.parquet`
- `party-dropout` — `data/party_dropout.parquet`
- `feature-drift` — `data/feature_drift.parquet`

## Quick start

```python
from datasets import load_dataset

core = load_dataset(
    "{DATASET_ID}",
    "core-model-comparison",
    split="benchmark",
)

overlap = load_dataset(
    "{DATASET_ID}",
    "partial-overlap",
    split="benchmark",
)

print(core.to_pandas())
print(overlap.to_pandas())
```

For a visual walkthrough of the same evidence, open the [interactive VertiMosaic Space]({SPACE_URL}).

## Evidence and provenance

Every published benchmark row carries the fixed experiment seed, source type, `raw_features_pooled` boundary and Git source commit. `summaries/manifest.json` records the canonical generation parameters and timestamp.

- Generated at: `{generated_at}`
- Source commit: `{source_commit}`
- Source repository: {SOURCE_URL}
- Reference model bundle: {MODEL_URL}

Timing and RSS fields are environment-dependent measurements from the GitHub Actions runner used for that publication. They should not be interpreted as hardware-independent performance claims.

## Privacy boundary

VertiMosaic keeps party feature matrices inside party objects during the reference VFL protocols and records communication metadata. This research simulator does **not** claim cryptographic security, private set intersection, MPC, homomorphic encryption, secure aggregation, collusion resistance, malicious-party security, or formal differential privacy.

## External-source policy

No UCI, OpenML, or IEEE-CIS source rows are redistributed in this Hugging Face dataset. The Apache-2.0 declaration applies to VertiMosaic-generated benchmark artifacts and does not relicense third-party data.

The separate four-industry external research benchmark is explicitly **semi-synthetic**: its public Bank, Telecom, Insurance and Retail sources do not represent the same real people. The optional IEEE-CIS mode uses user-supplied authorized local files and does not redistribute those files here.

## Intended use

Use this dataset to reproduce and inspect VertiMosaic's VFL behavior, communication cost, party contribution, entity-overlap robustness, party availability and controlled drift experiments. It should not be treated as evidence of production privacy, fairness, security, regulatory compliance or real-world causal effects.
"""


def _model_card(root: Path) -> str:
    metadata = _load_json(root / "metadata.json")
    evaluation = _load_json(root / "evaluation.json")
    by_name = {str(row.get("model")): row for row in evaluation}
    logistic = by_name.get("vfl_logistic", {})
    gbdt = by_name.get("vfl_hist_gbdt", {})
    source_commit = str(metadata.get("source_commit", "unknown"))
    benchmark = metadata.get("benchmark", {})
    rows = benchmark.get("rows", 800)
    seed = benchmark.get("seed", 42)
    train_rows = benchmark.get("train_rows", 560)
    validation_rows = benchmark.get("validation_rows", 120)
    test_rows = benchmark.get("test_rows", 120)

    return f"""---
license: apache-2.0
library_name: vertimosaic
pipeline_tag: tabular-classification
tags:
- federated-learning
- vertical-federated-learning
- tabular
- cpu
- reproducibility
- privacy-research
- logistic-regression
- gradient-boosting
datasets:
- {DATASET_ID}
---

# VertiMosaic VFL Reference Models

**Portable, deterministic CPU reference checkpoints for VertiMosaic vertical federated learning.**

[🚀 Explore results in the Space]({SPACE_URL}) · [📊 Open the benchmark dataset]({DATASET_URL}) · [💻 Source code]({SOURCE_URL})

This repository contains two research checkpoints generated from the VertiMosaic source tree:

- `VFLLogisticRegression` — first-principles vertical logistic regression.
- `VFLHistGBDT` — vertical histogram gradient boosting with party-local routing state.

They are deliberately small, inspectable reference artifacts rather than opaque production binaries.

## At a glance

| Item | Reference bundle |
|---|---|
| Checkpoints | 2 |
| Benchmark population | **{rows} aligned entities** |
| Seed | `{seed}` |
| Entity split | {train_rows} train / {validation_rows} validation / {test_rows} test |
| Logistic release setting | `max_iter=150` |
| GBDT release setting | `n_estimators=8` |
| Runtime target | CPU-first |
| Round-trip validation | prediction-level for both formats |
| Source commit | `{source_commit}` |

## Held-out reference evaluation

| Checkpoint | ROC-AUC | PR-AUC | F1 | Brier |
|---|---:|---:|---:|---:|
| VFL Logistic | {_fmt_metric(logistic, "roc_auc")} | {_fmt_metric(logistic, "pr_auc")} | {_fmt_metric(logistic, "f1")} | {_fmt_metric(logistic, "brier")} |
| VFL HistGBDT | {_fmt_metric(gbdt, "roc_auc")} | {_fmt_metric(gbdt, "pr_auc")} | {_fmt_metric(gbdt, "f1")} | {_fmt_metric(gbdt, "brier")} |

These are single deterministic synthetic benchmark measurements, not a leaderboard and not evidence that VFL generally outperforms centralized learning.

## What is in the repository?

| Path | Purpose |
|---|---|
| `logistic/model.json` | coordinator-visible logistic configuration and per-party weights |
| `gbdt/model.json` | ensemble topology, leaf values and opaque party/feature/bin references |
| `gbdt/parties/*.json` | synthetic party-local routing thresholds kept as **separate party shards** |
| `evaluation.json` | held-out metrics, validation-selected thresholds and prediction digests |
| `metadata.json` | source commit, split sizes and exact generation configuration |

The JSON formats are intentionally inspectable so the published checkpoints can be independently validated.

## Inspect locally

```python
import json
from pathlib import Path

evaluation = json.loads(Path("evaluation.json").read_text())
metadata = json.loads(Path("metadata.json").read_text())

print(evaluation)
print(metadata["source_commit"])
```

To regenerate the complete bundle from source:

```bash
git clone https://github.com/sauravsingla/VertiMosaic.git
cd VertiMosaic
python -m pip install -e .
SOURCE_SHA=$(git rev-parse HEAD) python huggingface/build_model.py --output hf-model
```

The builder performs prediction-level round-trip checks for both checkpoint formats before the package is published.

## Privacy and deployment boundary

The reference VertiMosaic protocols keep raw party feature matrices local, but that does **not** imply end-to-end cryptographic privacy. Gradient, Hessian, residual, logit, routing, timing and transport information can remain outside stronger privacy guarantees depending on the path used.

For the public synthetic GBDT checkpoint, train-derived routing thresholds are published as **separate party shards** for reproducibility. Real organizations should not centralize or publicly release analogous private party-local routing state merely because this synthetic research artifact does so.

These checkpoints are **not production models**, are not trained on real organizational data, and should not be used to make real-world decisions.

## Follow the evidence

- Interactive Space: {SPACE_URL}
- Benchmark dataset: {DATASET_URL}
- Source repository: {SOURCE_URL}
- PyPI: https://pypi.org/project/vertimosaic/

Generated from source commit `{source_commit}`.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Render polished Hugging Face cards")
    subparsers = parser.add_subparsers(dest="kind", required=True)

    dataset_parser = subparsers.add_parser("dataset")
    dataset_parser.add_argument("--root", type=Path, default=Path("hf-dataset"))

    model_parser = subparsers.add_parser("model")
    model_parser.add_argument("--root", type=Path, default=Path("hf-model"))

    args = parser.parse_args()
    root: Path = args.root
    card = _dataset_card(root) if args.kind == "dataset" else _model_card(root)
    (root / "README.md").write_text(card, encoding="utf-8")


if __name__ == "__main__":
    main()
