const METRICS={roc_auc:'ROC-AUC',pr_auc:'PR-AUC',f1:'F1',log_loss:'Log loss',brier:'Brier score',ece:'ECE'};
const LOWER_IS_BETTER=new Set(['log_loss','brier','ece']);
let DATA=null;
const f=(v,d=4)=>v==null||Number.isNaN(Number(v))?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:d});
const bytes=v=>v==null?'—':Number(v)>=1024*1024?(v/1024/1024).toLocaleString(undefined,{maximumFractionDigits:2})+' MiB':(v/1024).toLocaleString(undefined,{maximumFractionDigits:1})+' KiB';
const esc=s=>String(s??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const labelMetric=m=>METRICS[m]||m;
const metricOptions=()=>Object.entries(METRICS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1800)}
function observedExtreme(rows,metric='roc_auc'){const valid=(rows||[]).filter(r=>Number.isFinite(Number(r[metric])));if(!valid.length)return null;return valid.reduce((a,b)=>LOWER_IS_BETTER.has(metric)?Number(a[metric])<Number(b[metric])?a:b:Number(a[metric])>Number(b[metric])?a:b)}
function chart(rows,labelKey,metric){
  if(!rows?.length)return '<div class="sub">No evidence rows available for this selection.</div>';
  const vals=rows.map(r=>Number(r[metric])).filter(Number.isFinite);if(!vals.length)return '<div class="sub">This metric is not available for these rows.</div>';
  const max=Math.max(...vals),min=Math.min(...vals),span=Math.max(max-min,1e-12);
  return '<div class="chart">'+rows.map(r=>{const v=Number(r[metric]);const width=Number.isFinite(v)?Math.max(4,LOWER_IS_BETTER.has(metric)?100-(100*(v-min)/span):12+(88*(v-min)/span)):0;return `<div class="row"><div class="label" title="${esc(r[labelKey])}">${esc(r[labelKey])}</div><div class="track" title="${esc(labelMetric(metric))}: ${f(v)}"><div class="fill" style="width:${width}%"></div></div><div class="value">${f(v)}</div></div>`}).join('')+'</div><div class="metric-note">'+(LOWER_IS_BETTER.has(metric)?'Shorter bars indicate lower values; lower is generally preferable for this metric.':'Longer bars indicate higher observed values within this view.')+'</div>';
}
function insightCards(rows,labelKey){
  const roc=observedExtreme(rows,'roc_auc');const pr=observedExtreme(rows,'pr_auc');
  return `<div class="insights"><div class="insight"><small>Highest observed ROC-AUC</small><b>${roc?f(roc.roc_auc):'—'}</b><span>${roc?esc(roc[labelKey]):'No data'}</span></div><div class="insight"><small>Highest observed PR-AUC</small><b>${pr?f(pr.pr_auc):'—'}</b><span>${pr?esc(pr[labelKey]):'No data'}</span></div><div class="insight"><small>Evidence rows</small><b>${f(rows?.length||0,0)}</b><span>in this experiment family</span></div></div>`;
}
function renderModels(){
  const rows=DATA.core_model_comparison||[];
  document.querySelector('#models').innerHTML=`${insightCards(rows,'model')}<div class="grid"><div class="card"><h2>Core model comparison</h2><div class="sub">Same synthetic vertical population and fixed seed. Change the metric to compare the reference model paths from another angle.</div><div class="controls"><label>Metric <select id="modelMetric">${metricOptions()}</select></label></div><div id="modelChart"></div></div><div class="card"><h2>Quality + communication at a glance</h2><div class="metric-grid">${rows.map(r=>`<div class="metric accent"><b>${f(r.roc_auc)}</b><span>${esc(r.model)} · ROC-AUC</span></div><div class="metric"><b>${f(r.pr_auc)}</b><span>${esc(r.model)} · PR-AUC</span></div><div class="metric"><b>${bytes(r.estimated_communication_bytes)}</b><span>${esc(r.model)} · estimated communication</span></div>`).join('')}</div></div></div>`;
  const upd=()=>document.querySelector('#modelChart').innerHTML=chart(rows,'model',document.querySelector('#modelMetric').value);document.querySelector('#modelMetric').onchange=upd;upd();
}
function renderParties(){
  const rows=DATA.party_ablation||[];
  document.querySelector('#parties').innerHTML=`${insightCards(rows,'parties')}<div class="grid"><div class="card"><h2>Party ablation</h2><div class="sub">Bank is active. Telecom, Insurance and Retail are added in valid passive-party subsets so you can inspect the measured contribution pattern in this synthetic benchmark.</div><div class="controls"><label>Metric <select id="partyMetric">${metricOptions()}</select></label></div><div id="partyChart"></div></div><div class="card"><h2>Measured combinations</h2><div class="notice privacy">These results are descriptive evidence for the synthetic party-role setup. They do not imply that the same industries or feature groups will provide the same utility in real deployments.</div><div style="height:14px"></div><div class="table-wrap"><table><thead><tr><th>Parties</th><th>ROC-AUC</th><th>PR-AUC</th><th>F1</th><th>Comm.</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.parties)}</td><td>${f(r.roc_auc)}</td><td>${f(r.pr_auc)}</td><td>${f(r.f1)}</td><td>${bytes(r.estimated_communication_bytes)}</td></tr>`).join('')}</tbody></table></div></div></div>`;
  const upd=()=>document.querySelector('#partyChart').innerHTML=chart(rows,'parties',document.querySelector('#partyMetric').value);document.querySelector('#partyMetric').onchange=upd;upd();
}
function renderOverlap(){
  const rows=DATA.partial_overlap||[];
  document.querySelector('#overlap').innerHTML=`${insightCards(rows.map(r=>({...r,_label:`${r.method} · ${f(100*r.overlap_fraction,0)}%`})),'_label')}<div class="card"><h2>Partial entity overlap</h2><div class="sub">Compare intersection-only and availability-indicator approaches as common-entity coverage changes.</div><div class="controls"><label>Metric <select id="overlapMetric">${metricOptions()}</select></label><label>Method <select id="overlapMethod"><option value="all">Both methods</option><option value="intersection_only">Intersection only</option><option value="availability_indicator">Availability indicator</option></select></label></div><div id="overlapChart"></div><div style="height:18px"></div><div class="table-wrap"><table><thead><tr><th>Method / overlap</th><th>Coverage</th><th>Retained entities</th><th>ROC-AUC</th><th>PR-AUC</th><th>F1</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.method)} · ${f(100*r.overlap_fraction,0)}%</td><td>${f(100*r.coverage,1)}%</td><td>${f(r.retained_entities,0)}</td><td>${f(r.roc_auc)}</td><td>${f(r.pr_auc)}</td><td>${f(r.f1)}</td></tr>`).join('')}</tbody></table></div></div>`;
  const upd=()=>{const method=document.querySelector('#overlapMethod').value;const sub=(method==='all'?rows:rows.filter(r=>r.method===method)).map(r=>({...r,_label:`${r.method} · ${f(100*r.overlap_fraction,0)}%`}));document.querySelector('#overlapChart').innerHTML=chart(sub,'_label',document.querySelector('#overlapMetric').value)};document.querySelector('#overlapMetric').onchange=upd;document.querySelector('#overlapMethod').onchange=upd;upd();
}
function renderDropout(){
  const rows=DATA.party_dropout||[];
  document.querySelector('#dropout').innerHTML=`${insightCards(rows,'scenario')}<div class="card"><h2>Party availability and dropout</h2><div class="sub">Separate inference-time dropout from training-and-inference availability scenarios, then compare the observed metric response.</div><div class="controls"><label>Metric <select id="dropMetric">${metricOptions()}</select></label><label>Phase <select id="dropPhase"><option value="inference_time_dropout">Inference-time dropout</option><option value="training_and_inference_availability">Training + inference availability</option><option value="all">All phases</option></select></label></div><div id="dropChart"></div><div style="height:18px"></div><div class="table-wrap"><table><thead><tr><th>Scenario</th><th>Phase</th><th>Dropped</th><th>Available</th><th>ROC-AUC</th><th>PR-AUC</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.scenario)}</td><td>${esc(r.phase)}</td><td>${esc(r.dropped_parties||'none')}</td><td>${esc(r.available_parties)}</td><td>${f(r.roc_auc)}</td><td>${f(r.pr_auc)}</td></tr>`).join('')}</tbody></table></div></div>`;
  const upd=()=>{const phase=document.querySelector('#dropPhase').value;const sub=phase==='all'?rows:rows.filter(r=>r.phase===phase);document.querySelector('#dropChart').innerHTML=chart(sub,'scenario',document.querySelector('#dropMetric').value)};document.querySelector('#dropMetric').onchange=upd;document.querySelector('#dropPhase').onchange=upd;upd();
}
function renderDrift(){
  const rows=DATA.feature_drift||[];
  document.querySelector('#drift').innerHTML=`${insightCards(rows,'scenario')}<div class="grid"><div class="card"><h2>Controlled feature drift</h2><div class="sub">Mean, variance, missingness and categorical-frequency shifts are applied to selected synthetic parties.</div><div class="controls"><label>Metric <select id="driftMetric">${metricOptions()}</select></label></div><div id="driftChart"></div></div><div class="card"><h2>Scenario parameters</h2><div class="table-wrap"><table><thead><tr><th>Scenario</th><th>Party</th><th>Mean</th><th>Variance</th><th>Missingness</th><th>Category shift</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.scenario)}</td><td>${esc(r.party)}</td><td>${f(r.mean_shift,2)}</td><td>${f(r.variance_scale,2)}</td><td>${f(r.missingness_increase,2)}</td><td>${r.categorical_frequency_shift?'yes':'no'}</td></tr>`).join('')}</tbody></table></div></div></div>`;
  const upd=()=>document.querySelector('#driftChart').innerHTML=chart(rows,'scenario',document.querySelector('#driftMetric').value);document.querySelector('#driftMetric').onchange=upd;upd();
}
function renderSystems(){
  const rows=DATA.core_model_comparison||[];
  const commit=String(DATA.source_commit||'');
  document.querySelector('#systems').innerHTML=`<div class="grid"><div class="card"><h2>Systems measurements</h2><div class="sub">Environment-dependent measurements from the publication runner. Compare within this run; do not treat them as hardware-independent performance claims.</div><div class="table-wrap"><table><thead><tr><th>Model</th><th>Train s</th><th>Infer s</th><th>Peak RSS</th><th>Comm.</th><th>Messages</th><th>Scalars</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.model)}</td><td>${f(r.training_seconds,3)}</td><td>${f(r.inference_seconds,3)}</td><td>${r.peak_rss_bytes?bytes(r.peak_rss_bytes):'—'}</td><td>${bytes(r.estimated_communication_bytes)}</td><td>${f(r.communication_message_count,0)}</td><td>${f(r.communication_scalar_count,0)}</td></tr>`).join('')}</tbody></table></div></div><div class="card"><h2>Provenance + claim boundaries</h2><div class="metric-grid"><div class="metric accent"><b>${esc(commit.slice(0,7)||'—')}</b><span>Git source commit</span></div><div class="metric"><b>${esc(DATA.benchmark?.seed??'—')}</b><span>fixed seed</span></div><div class="metric"><b>${esc(DATA.schema_version??'—')}</b><span>payload schema</span></div></div><div style="height:15px"></div><div class="notice privacy">VertiMosaic demonstrates raw-feature locality in a research VFL simulator. It does not claim cryptographic privacy, private set intersection, MPC, homomorphic encryption, secure aggregation, collusion resistance, malicious-party security or formal differential privacy.</div><div style="height:12px"></div><div class="notice">This Space redistributes no UCI, OpenML or IEEE-CIS source rows. The separate four-industry external benchmark is semi-synthetic; those public datasets do not describe the same real individuals.</div><div class="provenance-actions"><button class="btn" type="button" id="copyCommit">Copy source commit</button><a class="btn" href="data.json" target="_blank">Open evidence JSON ↗</a></div></div></div>`;
  const copy=document.querySelector('#copyCommit');if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText(commit);toast('Source commit copied')}catch{toast('Copy unavailable in this browser')}};
}
function activateTab(id,{scroll=false,hash=true}={}){
  const btn=document.querySelector(`.tab[data-tab="${id}"]`);const section=document.getElementById(id);if(!btn||!section)return;
  document.querySelectorAll('.tab').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-selected','false')});document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));
  btn.classList.add('active');btn.setAttribute('aria-selected','true');section.classList.add('active');if(hash)history.replaceState(null,'',`#${id}`);if(scroll)document.querySelector('#explorer').scrollIntoView({behavior:'smooth',block:'start'});
}
function activateTabs(){document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>activateTab(btn.dataset.tab,{hash:true}));document.querySelectorAll('[data-go]').forEach(btn=>btn.onclick=()=>activateTab(btn.dataset.go,{scroll:true,hash:true}));document.querySelector('#storyStart').onclick=()=>activateTab('models',{scroll:true,hash:true});}
function setupTheme(){const root=document.documentElement;let saved=null;try{saved=localStorage.getItem('vertimosaic-theme')}catch{}const preferred=window.matchMedia?.('(prefers-color-scheme: light)').matches?'light':'dark';root.dataset.theme=saved||preferred;const btn=document.querySelector('#themeToggle');const sync=()=>{btn.textContent=root.dataset.theme==='dark'?'☼':'☾';btn.title=root.dataset.theme==='dark'?'Switch to light theme':'Switch to dark theme'};btn.onclick=()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('vertimosaic-theme',root.dataset.theme)}catch{}sync()};sync()}
async function init(){
  activateTabs();setupTheme();
  try{
    const r=await fetch('data.json',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);DATA=await r.json();
    document.querySelector('#loading').style.display='none';document.querySelector('#fact-core').textContent=f(DATA.benchmark?.core_rows,0);document.querySelector('#fact-seed').textContent=esc(DATA.benchmark?.seed??'—');
    renderModels();renderParties();renderOverlap();renderDropout();renderDrift();renderSystems();
    const generated=DATA.generated_at_utc||'—';document.querySelector('#freshness').textContent=`Generated ${generated}`;document.querySelector('#footerText').textContent=`Evidence generated ${generated} · source ${String(DATA.source_commit||'').slice(0,12)||'—'}`;
    const initial=location.hash.replace('#','');if(['models','parties','overlap','dropout','drift','systems'].includes(initial))activateTab(initial,{hash:false});
  }catch(e){document.querySelector('#loading').innerHTML=`<strong>Unable to load benchmark evidence.</strong><br>${esc(e.message)} · You can still inspect the project source and dataset from the links above.`}
}
init();
